[package]
name = "basilisc-base"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
arrayvec = { workspace = true }
ascii = { workspace = true }
static_assertions = { workspace = true }
