[package]
name = "basc"
version = "0.1.0"
edition = "2021"
authors = ["Simon Harris <simon@pearfalse.com>"]

[workspace]
resolver = "2"
members = ["crates/basc-macros"]

[dependencies]
gumdrop = "0.8"
ascii = "1.0"
arrayvec = "0.7.2"
thiserror = "1.0"
sealed = "0.4"

basc-macros = { path = "crates/basc-macros", version = "*" }
