[package]
name = "basc"
version = "0.1.0"
edition = "2021"
authors = ["Simon Harris <simon@pearfalse.com>"]

[dependencies]
gumdrop = "0.8"
ascii = "1.0"
arrayvec = "0.7.2"
thiserror = "1.0"
phf = "0.11"

[dev-dependencies]
phf_codegen = "0.11"
