[package]
name = "token-data-gen"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
arrayvec = { workspace = true }
ascii = { workspace = true }
basilisc-base = { path = "../basilisc-base" }
nonzero_ext = { workspace = true }
